Add husky and lint-staged
ocw-central/ocw-central-frontend pull request #120
Opened 2022-10-19 10:46 UTC by sj-h4

## Related Issue

## What

- [husky](https://github.com/typicode/husky) と [lint-staged](https://github.com/okonet/lint-staged) を追加しました（毎回 `yarn lint` を実行する手間を省くため）

## Memo

yarn v2 にした場合、 prepare が使えなくなるので postinstall を代わりに使う必要があります。

もし使えそうなら使っていただけるとありがたいです。

2022-10-20 06:40 UTC, yasutak requested changes
プルリクいただきどうもありがとうございます。huskyとても便利ですね。

~マージする前にお願いしたいのですが、mainではなくdevにコミットしてもらってよろしいでしょうか。~

2022-10-20 08:03 UTC, yasutak submitted a review, later dismissed

2022-10-20 11:54 UTC, roottool commented
リポジトリの設定で、デフォルトブランチをdevにすると良さそうです！
デフォルトブランチに設定されるとPRの初期設定として、対象ブランチがPRのマージ先になるので。

https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

2022-10-20 12:33 UTC, ooyamatakehisa commented
@roottool ありがとうございます．変更しておきました🙇

2022-10-20 12:35 UTC, roottool commented
### CI等開発環境以外でのhuskyの取り扱い

[緩やかな指摘(In my opinion)](https://qiita.com/kuniyonkunisan/items/2ed8c48ff349e6add45b)ですが、CIや本番環境では無効にする場合は、[公式ドキュメントの4パターン](https://typicode.github.io/husky/#/?id=disable-husky-in-cidockerprod)のいずれかを行っておくことをオススメします！
今の `yarn prepare` のままですと、デプロイやCI実行時の `yarn install` でも実行されてしまうので。

2022-10-21 17:11 UTC, shibukazu approved these changes
https://developers.cloudflare.com/pages/platform/build-configuration/
CloudFlarePagesの環境変数は以上のとおりでした。
環境変数にもとづきlint-stagedの実行を制御します。

2022-10-21 17:32 UTC, shibukazu requested changes
@yasutak 
pre-commitを以下のように変更するべきだと思います。
変更の上代わりにpushお願いします...
```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
[ -n "$CF_PAGES" ] && exit 0
yarn lint-staged
```

2022-10-22 05:01 UTC, shibukazu approved these changes
こちらで変更しました

2022-10-22 05:02 UTC, merged